language: node_js
jobs:
  include:
    - stage: Build
      script: exit 0
notifications:
  webhooks: https://3a49214f.ngrok.io/api/v1/organizations/1/webhook
  on_success: always
  on_failure: always
